### ISSUE TITLE
Docker Compose examples?

### ISSUE THREAD

**Issue by umbongodrink** [elgeeko1/roon-server-docker#1]
Hello, 

would it be possible please to get examples of running Roon in Docker using docker compose? 

It would be great to get examples for the three Options you have put in the docker run examples, and especially where we put the "additional functionality" USB/ALSA devices in the docker compose format. 

Thank you very much.

**Comment by elgeeko-creator** [comment]
Thanks for the suggestion! I'm afraid I won't have time to create this example for a while. docker-compose is a more advanced tool than the audience I target with this repo. Typically the Dockerfile is pretty straightforward to migrate to docker-compose. Good luck!

**Comment by elgeeko1** [comment]
Thanks for the suggestion! I'm afraid I won't have time to create this example for a while. docker-compose is a more advanced tool than the audience I target with this repo. Typically the Dockerfile is pretty straightforward to migrate to docker-compose. Good luck!

**Comment by begna112** [comment]
As you said, it's fairly easy to convert. Here's an example bridge networking one you might use. Compose uses bridge by default.

```
version: '3'
services:
  roon:
    container_name: roon
    image: elgeeko/roon-server
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "9003:9003/udp"
      - "9100-9200:9100-9200/tcp"
      - "9001-9002:9001-9002/tcp"
      - "9330-9339:9330-9339/tcp"
      - "30000-30010:30000-30010/tcp"
      - "49863:49863/tcp"
      - "52667:52667/tcp"
      - "52709:52709/tcp"
      - "63098-63100:63098-63100/tcp"
    volumes:
      - roon-server-data:/opt/RoonServer
      - roon-server-cache:/var/roon
      - [path to your music locally]:/music:ro
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    device:
      - /dev/bus/usb
      - /dev/snd

volumes:
  roon-server-data:
    name: roon-server-data
  roon-server-cache:
    name: roon-server-cache
```
