### ISSUE TITLE
Checks fail with "Testing ulimit -n 8192 [ FAILED ]"

### ISSUE THREAD

**Issue by troubleshootme** [elgeeko1/roon-server-docker#12]
Can't seem to get this to run properly. 

Here's my docker compose:

```
services:
  roon:
    container_name: roon-server
    image: elgeeko/roon-server:latest
    restart: unless-stopped
    privileged: true
    command: '--ulimit nofile=8192'

      
        
    volumes:
      - /volume1/Music:/music:ro # TODO: replace ~/music with your music directory
      - roon-server-data:/opt/RoonServer
      - roon-server-cache:/var/roon
     # - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    networks:
      - npm
    ports:
     - "9003:9003/udp"               # multicast
     - "9100-9200:9100-9200/tcp"     # RAAT
     - "9001-9002:9001-9002/tcp"     # ?
     - "9330-9339:9330-9339/tcp"     # ?
     - "30000-30010:30000-30010/tcp" # Chromecast
     - "49863:49863/tcp"             # ?
     - "52667:52667/tcp"             # ?
     - "52709:52709/tcp"             # ?
     - "63098-63100:63098-63100/tcp" # ?

volumes:
  roon-server-data:
    name: roon-server-data
  roon-server-cache:
    name: roon-server-cache
networks:
  npm:
    external: true
```
